import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/util/Providers";
import { Masthead } from "../components/masthead";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DarrowCraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Masthead/>
        <main className="py-6 px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
